name: CI SonarQube Analysis DEV

on:
  push:


jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Compilar y ejecutar tests con Maven
        working-directory: API
        run: mvn clean test verify

      - name: Ejecutar an√°lisis en SonarQube
        working-directory: API
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=RoutineFights \
            -Dsonar.host.url=http://zombiesurvive.ddns.net:9000 \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.qualitygate.wait=true  \
            -Dsonar.branch.name=$BRANCH_NAME
  build:
    needs: checks
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Create Maven Package
      run: mvn -f API/pom.xml clean package -DskipTests
    
    - name: Build and push java image
      uses: docker/build-push-action@v6
      with:
        context: API
        file: API/Dockerfile
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/apiroutinefights:latest

    - name: Debug
      run: |
          ls
          ls administration
    - name: Build and push admin image
      uses: docker/build-push-action@v6
      with:
        context: administration
        file: administration/Dockerfile
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/administrationroutinefights:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    steps:
    - name: Deploy to digitalocean
      uses: appleboy/ssh-action@master
      with:
        username: ${{ vars.HOSTING_USERNAME }}
        host: ${{ vars.HOSTING_PC }}
        key: ${{ secrets.HOSTING_KEY }}
        script: |
            docker compose down;
            docker compose pull
            docker image prune -f
            docker compose up -d
