name: CI SonarQube Analysis DEV

on:
  push:


jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Compilar y ejecutar tests con Maven
        working-directory: API
        run: mvn verify

      - name: Ejecutar anÃ¡lisis en SonarQube
        working-directory: API
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
          BRANCH_NAME: ${{ github.ref_name }}
          HOSTNAME: ${{ vars.HOSTING_PC }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=RoutineFights \
            -Dsonar.host.url=http://$HOSTNAME:9000 \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.qualitygate.wait=true  \
            -Dsonar.branch.name=$BRANCH_NAME
      - name: Save Maven build output
        if: success() && ${{ github.ref_name == 'main' }}
        uses: actions/upload-artifact@v4
        with:
          name: api-jar
          path: API/target/*.jar

  build:
    needs: checks
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    strategy:
      matrix:
        include:
        - name: API
          slug: api
          component: API
        - name: administration
          slug: administration
          component: administration
    steps:
      - uses: actions/checkout@v3

      - name: Create TIMESTAMP
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
      
      - name: Download Maven artifact
        uses: actions/download-artifact@v4
        with:
          name: api-jar
          path: API/target
      
      - uses: docker/setup-buildx-action@v2
      
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
     
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.component }}
          file: ${{ matrix.component }}/Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.slug }}routinefights:latest,
            ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.slug }}routinefights:${{ env.TIMESTAMP }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    steps:
    - name: Deploy to digitalocean
      uses: appleboy/ssh-action@v0.1.7
      with:
        username: ${{ vars.HOSTING_USERNAME }}
        host: ${{ vars.HOSTING_PC }}
        password: ${{ secrets.HOSTING_PASSWORD }}
        script: |
            docker compose down;
            docker compose pull
            docker image prune -f
            docker compose up -d
