name: CI SonarQube Analysis DEV

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Compilar y ejecutar tests con Maven
        working-directory: API
        run: mvn clean test verify

      - name: Ejecutar an√°lisis en SonarQube
        working-directory: API
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=RoutineFights \
            -Dsonar.host.url=http://zombiesurvive.ddns.net:9000 \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.qualitygate.wait=true \
            -Dsonar.branch.name=$BRANCH_NAME
